create table if not exists public.comelec_discovery_tasks (
  id bigint generated by default as identity primary key,
  task_key text not null unique,
  task_type text not null check (task_type in ('province', 'municipality', 'barangay')),
  province_code text not null,
  locality_code text,
  status text not null default 'pending' check (status in ('pending', 'processing', 'done', 'failed')),
  attempts integer not null default 0,
  locked_at timestamptz,
  completed_at timestamptz,
  next_attempt_at timestamptz not null default now(),
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comelec_er_queue (
  precinct_id text primary key,
  province_code text not null,
  status text not null default 'pending' check (status in ('pending', 'processing', 'ready', 'failed')),
  attempts integer not null default 0,
  locked_at timestamptz,
  last_checked_at timestamptz,
  last_downloaded_at timestamptz,
  next_check_at timestamptz not null default now(),
  content_hash text,
  storage_path text,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists comelec_er_queue_due_idx
  on public.comelec_er_queue (status, next_check_at);

create table if not exists public.comelec_er_records (
  precinct_id text primary key references public.comelec_er_queue (precinct_id) on delete cascade,
  content_hash text not null,
  source_url text not null,
  storage_path text not null,
  payload_bytes integer not null,
  fetched_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('comelec-er-json', 'comelec-er-json', false)
on conflict (id) do nothing;

insert into public.comelec_discovery_tasks (task_key, task_type, province_code)
values
  ('province:0700000', 'province', '0700000'),
  ('province:3600000', 'province', '3600000'),
  ('province:7000000', 'province', '7000000'),
  ('province:8700000', 'province', '8700000'),
  ('province:8800000', 'province', '8800000'),
  ('province:9900000', 'province', '9900000')
on conflict (task_key) do nothing;

create or replace function public.claim_comelec_discovery_tasks(p_limit integer default 8)
returns setof public.comelec_discovery_tasks
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.comelec_discovery_tasks
  set status = 'pending', locked_at = null, updated_at = now()
  where status = 'processing' and locked_at < now() - interval '15 minutes';

  return query
  with picked as (
    select id
    from public.comelec_discovery_tasks
    where status = 'pending' and next_attempt_at <= now()
    order by id
    for update skip locked
    limit greatest(1, least(p_limit, 20))
  )
  update public.comelec_discovery_tasks task
  set status = 'processing', locked_at = now(), attempts = attempts + 1, updated_at = now()
  from picked
  where task.id = picked.id
  returning task.*;
end;
$$;

create or replace function public.claim_comelec_er_batch(p_limit integer default 25)
returns setof public.comelec_er_queue
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.comelec_er_queue
  set status = 'pending', locked_at = null, updated_at = now()
  where status = 'processing' and locked_at < now() - interval '15 minutes';

  return query
  with picked as (
    select precinct_id
    from public.comelec_er_queue
    where status in ('pending', 'ready') and next_check_at <= now()
    order by coalesce(last_checked_at, 'epoch'::timestamptz), precinct_id
    for update skip locked
    limit greatest(1, least(p_limit, 50))
  )
  update public.comelec_er_queue queue
  set status = 'processing', locked_at = now(), attempts = attempts + 1, updated_at = now()
  from picked
  where queue.precinct_id = picked.precinct_id
  returning queue.*;
end;
$$;

create or replace function public.requeue_comelec_discovery_if_due()
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  last_completed timestamptz;
begin
  select max(completed_at) into last_completed
  from public.comelec_discovery_tasks;

  if last_completed is not null
    and last_completed < now() - interval '24 hours'
    and not exists (select 1 from public.comelec_discovery_tasks where status in ('pending', 'processing')) then
    update public.comelec_discovery_tasks
    set status = 'pending', next_attempt_at = now(), locked_at = null, updated_at = now();
    return true;
  end if;

  return false;
end;
$$;

revoke all on function public.claim_comelec_discovery_tasks(integer) from public;
revoke all on function public.claim_comelec_er_batch(integer) from public;
revoke all on function public.requeue_comelec_discovery_if_due() from public;
